#
# Convert MC68881 FPU VHDL files to Verilog using ghdl
#
# The VHDL files are the canonical source (kept for easy updates from 68881-fpga).
# The generated Verilog files are used by verilator (which cannot read VHDL).
# For Quartus/FPGA synthesis, use the VHDL files directly via mc68881.qip.
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts/convert_to_verilog.ps1

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SrcDir = Join-Path $ScriptDir "..\src"
$OutDir = Join-Path $ScriptDir "..\verilog"
$GhdlPath = "C:\code\ghdl-mcode-5.1.1-mingw64\bin\ghdl.exe"

Push-Location $SrcDir

try {
    Write-Host "=== MC68881 FPU VHDL to Verilog Converter ==="
    Write-Host ""

    if (-not (Test-Path $GhdlPath)) {
        Write-Host "Error: ghdl not found at $GhdlPath"
        exit 1
    }

    $version = & $GhdlPath --version | Select-Object -First 1
    Write-Host "Using: $version"
    Write-Host "Output: $OutDir"
    Write-Host ""

    if (-not (Test-Path $OutDir)) {
        New-Item -ItemType Directory -Path $OutDir | Out-Null
    }

    $PackageFile = "mc68881_pkg.vhd"
    $TopFile = "mc68881_top.vhd"
    $UnitFiles = @(
        "mc68881_fp80_mul_unit.vhd"
        "mc68881_fp80_addsub_unit.vhd"
        "mc68881_modrem_post_unit.vhd"
        "mc68881_divrem_unit.vhd"
        "mc68881_sgl_ops_unit.vhd"
        "mc68881_trig_unit.vhd"
        "mc68881_packed_decimal_unit.vhd"
        "mc68881_alu.vhd"
    )

    # Clean previous ghdl work library
    Remove-Item -Path work-obj93.cf, work-obj08.cf -ErrorAction SilentlyContinue

    # ============================================================
    # Step 1: Analyze all VHDL files in dependency order
    # ============================================================
    Write-Host "=== Step 1: Analyzing VHDL files ==="

    Write-Host "  Analyzing package: $PackageFile"
    & $GhdlPath -a --std=08 -fsynopsys -fexplicit $PackageFile
    if ($LASTEXITCODE -ne 0) { throw "GHDL analyze failed: $PackageFile" }

    foreach ($f in $UnitFiles) {
        Write-Host "  Analyzing: $f"
        & $GhdlPath -a --std=08 -fsynopsys -fexplicit $f
        if ($LASTEXITCODE -ne 0) { throw "GHDL analyze failed: $f" }
    }

    Write-Host "  Analyzing: $TopFile"
    & $GhdlPath -a --std=08 -fsynopsys -fexplicit $TopFile
    if ($LASTEXITCODE -ne 0) { throw "GHDL analyze failed: $TopFile" }

    Write-Host ""

    # ============================================================
    # Step 2: Synthesize each entity to Verilog
    # ============================================================
    Write-Host "=== Step 2: Converting to Verilog ==="

    $convertCount = 0

    foreach ($f in $UnitFiles) {
        $entity = $f -replace '\.vhd$', ''
        $out = Join-Path $OutDir "$entity.v"
        Write-Host "  Converting: $f -> $out"
        & $GhdlPath synth --std=08 -fsynopsys -fexplicit --latches --out=verilog $entity | Out-File -Encoding ascii -FilePath $out
        if ($LASTEXITCODE -ne 0) { throw "GHDL synth failed: $entity" }
        $convertCount++
    }

    $entity = $TopFile -replace '\.vhd$', ''
    $out = Join-Path $OutDir "$entity.v"
    Write-Host "  Converting: $TopFile -> $out (with generics)"
    & $GhdlPath synth --std=08 -fsynopsys -fexplicit --latches --out=verilog $entity | Out-File -Encoding ascii -FilePath $out
    if ($LASTEXITCODE -ne 0) { throw "GHDL synth failed: $entity" }
    $convertCount++

    # --- Lite-mode top-level (fpu_lite_g => true) ---
    $LiteDir = Join-Path $OutDir "fpu_lite"
    if (-not (Test-Path $LiteDir)) {
        New-Item -ItemType Directory -Path $LiteDir | Out-Null
    }
    $out = Join-Path $LiteDir "$entity.v"
    Write-Host "  Converting: $TopFile -> $out (fpu_lite_g=true)"
    & $GhdlPath synth --std=08 -fsynopsys -fexplicit --latches --out=verilog "-gfpu_lite_g=true" $entity | Out-File -Encoding ascii -FilePath $out
    if ($LASTEXITCODE -ne 0) { throw "GHDL synth failed: $entity (lite)" }
    $convertCount++

    Write-Host ""

    # ============================================================
    # Step 3: Generate verilator QIP file
    # ============================================================
    Write-Host "=== Step 3: Generating mc68881_verilog.qip ==="

    $qipPath = Join-Path $OutDir "mc68881_verilog.qip"
    $qipLines = @(
        "# MC68881 FPU Verilog QIP file"
        "# Auto-generated by convert_to_verilog.ps1"
        "# For verilator only - Quartus should use mc68881.qip (VHDL sources)"
        ""
    )
    foreach ($f in $UnitFiles) {
        $entity = $f -replace '\.vhd$', ''
        $qipLines += "set_global_assignment -name VERILOG_FILE [file join `$::quartus(qip_path) $entity.v ]"
    }
    $entity = $TopFile -replace '\.vhd$', ''
    $qipLines += "set_global_assignment -name VERILOG_FILE [file join `$::quartus(qip_path) $entity.v ]"
    $qipLines | Out-File -Encoding ascii -FilePath $qipPath

    Write-Host "  Generated: $qipPath"
    Write-Host ""

    Write-Host "=== Step 4: Generating mc68881_pkg.sv stub ==="
    Write-Host "  Package types are inlined by ghdl - no separate .sv needed"
    Write-Host ""

    # Clean up ghdl work library
    Remove-Item -Path work-obj93.cf, work-obj08.cf -ErrorAction SilentlyContinue

    Write-Host "=== Conversion Complete ==="
    Write-Host "Converted $convertCount VHDL files to Verilog"
    Write-Host ""
    Write-Host "Files for verilator Makefile:"
    foreach ($f in $UnitFiles) {
        $entity = $f -replace '\.vhd$', ''
        Write-Host "  `$(RTL)/mc68881/$entity.v \"
    }
    $entity = $TopFile -replace '\.vhd$', ''
    Write-Host "  `$(RTL)/mc68881/$entity.v"

} finally {
    Pop-Location
}
