#!/bin/bash
#
# Convert MC68881 FPU VHDL files to Verilog using ghdl
#
# The VHDL files are the canonical source (kept for easy updates from 68881-fpga).
# The generated Verilog files are used by verilator (which cannot read VHDL).
# For Quartus/FPGA synthesis, use the VHDL files directly via mc68881.qip.
#
# Usage: ./convert_to_verilog.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/../src"
cd "$SRC_DIR"

echo "=== MC68881 FPU VHDL to Verilog Converter ==="
echo ""

# Check for ghdl
if ! command -v ghdl > /dev/null 2>&1; then
    echo "Error: ghdl not found in PATH"
    echo "Install: brew install ghdl  (macOS)"
    exit 1
fi

echo "Using: $(ghdl --version | head -1)"
echo ""

# Package file (analyzed first, not synthesized standalone)
PACKAGE_FILE="mc68881_pkg.vhd"

# Top-level entity (synthesized with generics)
TOP_FILE="mc68881_top.vhd"

# All other source files (leaf units, no special handling)
UNIT_FILES=(
    mc68881_fp80_mul_unit.vhd
    mc68881_fp80_addsub_unit.vhd
    mc68881_modrem_post_unit.vhd
    mc68881_divrem_unit.vhd
    mc68881_sgl_ops_unit.vhd
    mc68881_trig_unit.vhd
    mc68881_packed_decimal_unit.vhd
    mc68881_alu.vhd
)

# Clean previous ghdl work library
rm -rf work-obj93.cf work-obj08.cf 2>/dev/null || true

# ============================================================
# Step 1: Analyze all VHDL files in dependency order
# ============================================================
echo "=== Step 1: Analyzing VHDL files ==="

# Package first (all other files depend on it)
echo "  Analyzing package: $PACKAGE_FILE"
ghdl -a --std=08 -fsynopsys -fexplicit "$PACKAGE_FILE"

# Unit files (order doesn't matter — they only depend on the package)
for f in "${UNIT_FILES[@]}"; do
    echo "  Analyzing: $f"
    ghdl -a --std=08 -fsynopsys -fexplicit "$f"
done

# Top-level last (depends on ALU and packed_decimal_unit)
echo "  Analyzing: $TOP_FILE"
ghdl -a --std=08 -fsynopsys -fexplicit "$TOP_FILE"

echo ""

# ============================================================
# Step 2: Synthesize each entity to Verilog
# ============================================================
echo "=== Step 2: Converting to Verilog ==="

convert_count=0

for f in "${UNIT_FILES[@]}"; do
    entity="${f%.vhd}"
    out="${entity}.v"
    echo "  Converting: $f -> $out"
    ghdl synth --std=08 -fsynopsys -fexplicit --latches \
        --out=verilog "$entity" > "$out"
    convert_count=$((convert_count + 1))
done

# Top-level with generic parameters
entity="${TOP_FILE%.vhd}"
out="${entity}.v"
echo "  Converting: $TOP_FILE -> $out (with generics)"
ghdl synth --std=08 -fsynopsys -fexplicit --latches \
    --out=verilog "$entity" > "$out"
convert_count=$((convert_count + 1))

echo ""

# ============================================================
# Step 3: Generate verilator QIP file
# ============================================================
echo "=== Step 3: Generating mc68881_verilog.qip ==="

{
    echo "# MC68881 FPU Verilog QIP file"
    echo "# Auto-generated by convert_to_verilog.sh"
    echo "# For verilator only — Quartus should use mc68881.qip (VHDL sources)"
    echo ""
    for f in "${UNIT_FILES[@]}"; do
        echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) ${f%.vhd}.v ]"
    done
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) ${TOP_FILE%.vhd}.v ]"
} > mc68881_verilog.qip

echo "  Generated: mc68881_verilog.qip"
echo ""

# ============================================================
# Step 4: Generate SystemVerilog package stub for verilator
# ============================================================
echo "=== Step 4: Generating mc68881_pkg.sv stub ==="

# ghdl inlines package contents into each converted module, so verilator
# doesn't need a separate package file. But if any types/constants are
# needed externally (e.g. in the wrapper), we note that here.
echo "  Package types are inlined by ghdl — no separate .sv needed"

echo ""

# Clean up ghdl work library
rm -rf work-obj93.cf work-obj08.cf 2>/dev/null || true

echo "=== Conversion Complete ==="
echo "Converted $convert_count VHDL files to Verilog"
echo ""
echo "Files for verilator Makefile:"
for f in "${UNIT_FILES[@]}"; do
    echo "  \$(RTL)/mc68881/${f%.vhd}.v \\"
done
echo "  \$(RTL)/mc68881/${TOP_FILE%.vhd}.v"
