#!/usr/bin/env python3
from __future__ import annotations

from datetime import datetime, timezone
import mpmath as mp

mp.mp.dps = 200

FP80_EXP_BIAS = 16383


def round_ties_even(v: mp.mpf) -> int:
    base = int(mp.floor(v))
    frac = v - base
    if frac > mp.mpf("0.5"):
        return base + 1
    if frac < mp.mpf("0.5"):
        return base
    return base if (base % 2 == 0) else (base + 1)


def fp80_hex(x: mp.mpf) -> str:
    if mp.isnan(x):
        return "7FFFC000000000000001"
    if mp.isinf(x):
        return ("7FFF" if x > 0 else "FFFF") + "8000000000000000"
    if x == 0:
        return "00000000000000000000"

    sign = 1 if x < 0 else 0
    a = -x if x < 0 else x
    e = int(mp.floor(mp.log(a, 2)))
    m = a / mp.power(2, e)
    q = m * mp.power(2, 63)
    mant = round_ties_even(q)
    if mant == (1 << 64):
        mant >>= 1
        e += 1

    exp_field = e + FP80_EXP_BIAS
    if exp_field <= 0:
        raise ValueError("Subnormal/underflow not supported by this generator")
    if exp_field >= 0x7FFF:
        return ("7FFF" if sign == 0 else "FFFF") + "8000000000000000"

    bits = (sign << 79) | (exp_field << 64) | mant
    return f"{bits:020X}"


def fint_nearest_even(x: mp.mpf) -> mp.mpf:
    sign = -1 if x < 0 else 1
    a = -x if x < 0 else x
    n = int(mp.floor(a))
    frac = a - n
    if frac > mp.mpf("0.5"):
        n += 1
    elif frac == mp.mpf("0.5") and (n % 2 == 1):
        n += 1
    return mp.mpf(sign * n)


def fintrz(x: mp.mpf) -> mp.mpf:
    return mp.floor(x) if x >= 0 else mp.ceil(x)


def main() -> None:
    c = {
        "P0_5": mp.mpf("0.5"),
        "P0_6": mp.mpf("0.6"),
        "P0_75": mp.mpf("0.75"),
        "P0_9": mp.mpf("0.9"),
        "P1_1": mp.mpf("1.1"),
        "P1_25": mp.mpf("1.25"),
        "P1_7": mp.mpf("1.7"),
        "P2_4": mp.mpf("2.4"),
        "P3_7": mp.mpf("3.7"),
        "P9": mp.mpf("9.0"),
        "P12_5": mp.mpf("12.5"),
        "M0_7": mp.mpf("-0.7"),
        "M2_3": mp.mpf("-2.3"),
    }

    vals = {
        "GV_ARG_M2P3": c["M2_3"],
        "GV_ARG_M0P7": c["M0_7"],
        "GV_ARG_0P5": c["P0_5"],
        "GV_ARG_0P6": c["P0_6"],
        "GV_ARG_0P75": c["P0_75"],
        "GV_ARG_0P9": c["P0_9"],
        "GV_ARG_1P1": c["P1_1"],
        "GV_ARG_1P25": c["P1_25"],
        "GV_ARG_1P7": c["P1_7"],
        "GV_ARG_2": mp.mpf("2.0"),
        "GV_ARG_2P4": c["P2_4"],
        "GV_ARG_3P7": c["P3_7"],
        "GV_ARG_12P5": c["P12_5"],
        "GV_ARG_1234567": mp.mpf("1234567.0"),
        "GV_ARG_M2": mp.mpf("-2.0"),
        "GV_ADD_3P7_2P4": c["P3_7"] + c["P2_4"],
        "GV_SUB_M2P3_0P6": c["M2_3"] - c["P0_6"],
        "GV_MUL_3P7_2P4": c["P3_7"] * c["P2_4"],
        "GV_DIV_12P5_M0P7": c["P12_5"] / c["M0_7"],
        "GV_SQRT_9": mp.sqrt(c["P9"]),
        "GV_ABS_M2P3": mp.fabs(c["M2_3"]),
        "GV_NEG_1P1": -c["P1_1"],
        "GV_INTRZ_M2P3": fintrz(c["M2_3"]),
        "GV_INT_1P7": fint_nearest_even(c["P1_7"]),
        "GV_SIN_1P1": mp.sin(c["P1_1"]),
        "GV_COS_M2P3": mp.cos(c["M2_3"]),
        "GV_TAN_0P9": mp.tan(c["P0_9"]),
        "GV_ETOX_0P75": mp.e ** c["P0_75"],
        "GV_LOGN_1P25": mp.log(c["P1_25"]),
        "GV_TWOTOX_0P75": mp.power(2, c["P0_75"]),
        "GV_TENTOX_0P5": mp.power(10, c["P0_5"]),
        "GV_ATAN_2": mp.atan(mp.mpf("2.0")),
        "GV_ATAN_M2": mp.atan(mp.mpf("-2.0")),
        "GV_TANH_0P75": mp.tanh(c["P0_75"]),
        "GV_SIN_1234567": mp.sin(mp.mpf("1234567.0")),
        "GV_COS_1234567": mp.cos(mp.mpf("1234567.0")),
        "GV_TAN_1234567": mp.tan(mp.mpf("1234567.0")),
    }

    lines = []
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("use ieee.numeric_std.all;")
    lines.append("")
    lines.append("use work.mc68881_pkg.all;")
    lines.append("")
    lines.append("package mc68881_golden_vectors_pkg is")
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines.append(f"  -- Generated by scripts/gen_golden_vectors.py at {ts}.")
    lines.append("  -- Source: high-precision mpmath, rounded to IEEE-754 80-bit extended.")
    for name, value in vals.items():
        lines.append(f'  constant {name} : fp80_t := x"{fp80_hex(value)}";')
    lines.append("end package mc68881_golden_vectors_pkg;")
    lines.append("")

    out_path = "tb/mc68881_golden_vectors_pkg.vhd"
    with open(out_path, "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
