library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.mc68881_pkg.all;

package mc68881_golden_vectors_pkg is
  -- Generated by scripts/gen_golden_vectors.py at 2026-02-15 09:38:26Z.
  -- Source: high-precision mpmath, rounded to IEEE-754 80-bit extended.
  constant GV_ARG_M2P3 : fp80_t := x"C0009333333333333333";
  constant GV_ARG_M0P7 : fp80_t := x"BFFEB333333333333333";
  constant GV_ARG_0P5 : fp80_t := x"3FFE8000000000000000";
  constant GV_ARG_0P6 : fp80_t := x"3FFE999999999999999A";
  constant GV_ARG_0P75 : fp80_t := x"3FFEC000000000000000";
  constant GV_ARG_0P9 : fp80_t := x"3FFEE666666666666666";
  constant GV_ARG_1P1 : fp80_t := x"3FFF8CCCCCCCCCCCCCCD";
  constant GV_ARG_1P25 : fp80_t := x"3FFFA000000000000000";
  constant GV_ARG_1P7 : fp80_t := x"3FFFD99999999999999A";
  constant GV_ARG_2 : fp80_t := x"40008000000000000000";
  constant GV_ARG_2P4 : fp80_t := x"4000999999999999999A";
  constant GV_ARG_3P7 : fp80_t := x"4000ECCCCCCCCCCCCCCD";
  constant GV_ARG_12P5 : fp80_t := x"4002C800000000000000";
  constant GV_ARG_M2 : fp80_t := x"C0008000000000000000";
  constant GV_ADD_3P7_2P4 : fp80_t := x"4001C333333333333333";
  constant GV_SUB_M2P3_0P6 : fp80_t := x"C000B99999999999999A";
  constant GV_MUL_3P7_2P4 : fp80_t := x"40028E147AE147AE147B";
  constant GV_DIV_12P5_M0P7 : fp80_t := x"C0038EDB6DB6DB6DB6DB";
  constant GV_SQRT_9 : fp80_t := x"4000C000000000000000";
  constant GV_ABS_M2P3 : fp80_t := x"40009333333333333333";
  constant GV_NEG_1P1 : fp80_t := x"BFFF8CCCCCCCCCCCCCCD";
  constant GV_INTRZ_M2P3 : fp80_t := x"C0008000000000000000";
  constant GV_INT_1P7 : fp80_t := x"40008000000000000000";
  constant GV_SIN_1P1 : fp80_t := x"3FFEE4262A616B19BA80";
  constant GV_COS_M2P3 : fp80_t := x"BFFEAA9110B9817F0E68";
  constant GV_TAN_0P9 : fp80_t := x"3FFFA14CDD4E1509BE2A";
  constant GV_ETOX_0P75 : fp80_t := x"4000877CEDA33EE7BDEA";
  constant GV_LOGN_1P25 : fp80_t := x"3FFCE47FBE3CD4D10D61";
  constant GV_TWOTOX_0P75 : fp80_t := x"3FFFD744FCCAD69D6AF4";
  constant GV_TENTOX_0P5 : fp80_t := x"4000CA62C1D6D2DA9490";
  constant GV_ATAN_2 : fp80_t := x"3FFF8DB70C975DF22363";
  constant GV_ATAN_M2 : fp80_t := x"BFFF8DB70C975DF22363";
  constant GV_TANH_0P75 : fp80_t := x"3FFEA2991F2A9791413A";
end package mc68881_golden_vectors_pkg;
